title: Martichka9 Portfolio
email: kirilovamartina9@gmail.com
description: "Portfolio web page"
destination: docs
baseurl: "/Collection"
url: ""
twitter_username: jekyllrb
github_username:  jekyll

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package-lock.json
  - package.json
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
